---
- name: Add remote elklog server to rsyslog.conf
  hosts: all
  remote_user: root

  tasks:
  - name: Add extra entries of Syslog server to rsyslog.conf
    blockinfile:
      path: /etc/rsyslog.conf
      block: |
        *.info  @132.76.78.60:514
        *.*  @132.76.78.60:514
      backup: yes
    notify:
      - restart syslog

  handlers:
    - name: restart syslog
      service: name=syslog state=restarted