---
    - name: Install unzip
      dnf:
        name: unzip
        state: latest

    - name: Create /tmp/sep directory
      command: mkdir -p /tmp/sep/installation

    - name: Download SEP package
      uri:
        url: "{{ sep_url }}"
        dest: /tmp/sep
        method: GET

    - name: Extract SEP package contents
      unarchive:
        src:  /tmp/sep/LinuxInstaller.zip
        dest: /tmp/sep/installation
        remote_src: no

    - name: Find LinuxInstaller executable file
      find:
        paths: "/tmp/sep/installation"
        patterns: "LinuxInstaller"
        recurse: "yes"
      register: exec
      failed_when: exec.files[0].matched == 0

    - name: Install SEP AntiVirus
      vars:
        path: "{{ exec.files[0].path }}"
      command: "{{ path }}"
      register: sep_result
      ignore_errors: True

    - name: Fail the play if the SEP installation failed
      fail: msg="SEP installation failed"
      when: "sep_result.rc != 0 and sep_result.rc != 3"