---
- name: Prepare list of packages
  command: ls ../packages/subscription-manager/
  register: package_list

- name: Install subscription-manager
  yum: 
    name: ../packages/subscription-manager/"{{ item }}"
    state: present
  loop: package_list
