---
- name: Load Oracle Installation version
  set_fact:
    current_oracle: "{{ lookup('vars', orainst_ver) }}"

- name: Load PHP Installation version
  set_fact:
    currentphp: "{{ lookup('vars', php_ver) }}"

- name: Install Oracle basic
  uri:
    url: "{{ current_oracle.oracle_basic }}"

- name: Install Oracle devel
  uri:
    url: "{{ current_oracle.oracle_devel }}"

- name: Update /etc/environment with Variables
  blockinfile:
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
    path: /etc/environment
    block:   |
               export PHP_DTRACE=yes
               export ORACLE_HOME="{{ current_oracle.oraclelib_path }}"
               export LD_LIBRARY_PATH="{{ current_oracle.oraclelib_path }}"
          # export PATH=$PATH:"{{ lookup('vars', current_oracle.oracle_path) }}"

- name: Update /etc/bashrc to load Variables from /etc/environment
  blockinfile:     
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
    path: /etc/bashrc
    block:   |
             # Load Environment Variables 
             source /etc/environment

- name: Install pecl
  command: /bin/sh -c "pecl install {{ currentphp.oci8 }}"

- name: create OCI8 .ini file
  command: /bin/sh -c "echo 'extension=oci8.so' > /etc/php.d/90-oci8.ini"

        

           
         
