---
- name: Copy registration script to remote host
  copy:
    src: ../scripts/registerrh.sh
    dest: /tmp/registerrh.sh
    owner: ansible
    group: ansible
    mode: 0770

- name: Register host with Satellite
  command: /tmp/registerrh.sh   2>&1 /tmp/register.log
  async: 60
  poll: 10
     