---
- name: Copy registration script to remote host
  copy:
    src: ../scripts/registerrh.sh
    dest: /tmp/registerrh.sh
    owner: ansible
    group: ansible
    mode: 0770
    force: yes

- name: Register host with {{ capsule_fqdn }}
  command: /bin/bash -c "/tmp/registerrh.sh {{ capsule_fqdn }} > /tmp/registerrh.log"
  async: 120
  poll: 10
     