---
- name: Update ssl packages for curl
  yum:
    name: ../packages/ssl/"{{ item }}"
    state: latest
  async: 40
  poll: 5
  loop:
    - ca-certificates-2021.2.50-72.el7_9.noarch.rpm
    - nspr-4.32.0-1.el7_9.i686.rpm
    - ncurses-libs-5.9-14.20130511.el7_4.i686.rpm
    - nss-3.67.0-4.el7_9.i686.rpm
    - nss-3.67.0-4.el7_9.x86_64.rpm
    - nss-pem-1.0.3-7.el7.i686.rpm
    - nss-softokn-3.67.0-3.el7_9.i686.rpm
    - nss-util-3.67.0-1.el7_9.i686.rpm
    - readline-6.2-11.el7.i686.rpm
    - sqlite-3.7.17-8.el7_7.1.i686.rpm
    - curl-7.29.0-59.el7_9.1.x86_64.rpm