---
- name: Check if hosts.allow exists
  command: ls /etc/hosts.allow
  ignore_errors: true
  register: exists

- name: Check if any hosts are configured in hosts.allow
  when: exists.rc == 0
  command: /bin/bash -c "(cat /etc/hosts.allow | grep ^sshd) | wc -l"
  ignore_errors: true
  register: configuredhosts

- name: Add "{{ capsule_fqdn }}" to hosts.allow
  when: exists.rc == 0 and (configuredhosts.stdout | int) > 0
  blockinfile:
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      path: /etc/hosts.allow
      block: |
          # Satellite
          sshd : {{ capsule_fqdn }} : allow