---
nios_provider:
  host: "{{ nios_hostname }}"
  username: "{{ nios_user.split('@')[0] | lower }}"
  password: "{{ nios_password }}"
  wapi_version: '2.9.1'

nios_hostname: ipam.weizmann.ac.il
nios_user: '{{ lookup("env","SAT_USERNAME") }}'
nios_password: '{{ lookup("env","SAT_PASSWORD") }}'
