---
nios_provider:
  host: "{{ nios_hostname }}"
  username: "{{ nios_user }}"
  password: "{{ nios_password }}"
  wapi_version: '2.9'

nios_hostname: ipam.weizmann.ac.il
nios_user: "{{ vault_nios_user }}"
nios_password: "{{ vault_nios_password }}"
