---
- name: Configure system and connect to AD
  hosts: test
  become: yes
  remote_user: root

  tasks:
    - name: Install unzip
      yum:
        name: unzip
        state: latest

    - name: Download the latest package for SEP AntiVirus
      get_url:
        url: http://antivirus.weizmann.ac.il/Information%20System%20Division%20-%20IT/Linux%20Servers/latest.zip
        dest: /tmp/latest.zip

    - name: Extract SEP package contents
      command: /usr/bin/unzip /tmp/latest.zip -d sep

    - name: Find LinuxInstaller executable file
      find:
        paths: /tmp/sep
        patterns: 'LinuxInstaller'
        recurse: yes
        register: exec

      copy: 
        src: {{ exec }} 
        dest: /tmp
        owner: root
        mode: 0775
   
