---
- hosts: tower
  become: false
  remote_user: ansible
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault

  connection: local
  tasks:
    - name: Add new host record to Infoblox
      nios_host_record:
        name: "{{ hostname }}.weizmann.ac.il"
        ipv4addrs:
          - ipv4addr:
              "{{ lookup('nios_next_ip', {{ CIDR }}, provider=nios_provider)[0] }}"
        state: present
        comment: Created by Ansible Tower
        provider: "{{ nios_provider }}"
      register: status
      failed_when: "not status is search('already exists') and status.failed == true"

