---
- name: Add existing hosts to Satellite server
  hosts: all

  tasks: 
     
     - name: Copy registration script to remote host
       copy:
          src: ../scripts/registerrh8.sh
          dest: /tmp/registerrh8.sh
          owner: root
          group: root
          mode: 0770

     - name: Register host with Satellite
       command: /tmp/registerrh8.sh
     
     - name: Add hostname to autosign.conf
       lineinfile:
          insertafter: EOF
          path: /etc/puppetlabs/puppet/autosign.conf
          line: "{{ inventory_hostname }}.weizmann.ac.il"
       delegate_to: iblstlv01.weizmann.ac.il

     - name: Install puppet package
       yum:
          name: puppet
          state: latest

     - name: Copy puppet.conf to remote host
       copy:
          src: ../templates/puppet.conf
          dest: /etc/puppetlabs/puppet/puppet.conf
          owner: puppet
          group: puppet
          mode: 0644

     - name: Enable puppet service
       service:
          name: puppet
          state: restarted
          enabled: yes

     - name: Initiate puppet registration with Satellite server
       command: '/usr/bin/puppet agent -t --server iblstlv01.weizmann.ac.il'

