---
- name: Add existing hosts to Satellite server
  hosts: all

  tasks: 
     
     - name: Copy registration script to remote host
       copy:
          src: ../scripts/registerrh8.sh
          dest: /tmp/registerrh8.sh
          owner: root
          group: root
          mode: 0770

     - name: Register host with Satellite
       command: /tmp/registerrh8.sh
     
     - name: Add hostname to autosign.conf
       lineinfile:
          insertafter: EOF
          path: /etc/puppetlabs/puppet/autosign.conf
          line: "{{ inventory_hostname }}.weizmann.ac.il"
       delegate_to: iblstlv01.weizmann.ac.il

     - name: Install puppet agent
       yum:
          name: puppet-agent
          state: latest

     - name: Initiate puppet registration with Satellite server
       command: "puppet agent -t --server iblstlv01.weizmann.ac.il"

