---
- hosts: all
  become: true

  tasks: 

    # Copy Banner to remote host
      - name: Copy Banner to ssh daemon folder
        copy: 
          src: ../templates/sshd-banner
          dest: /etc/ssh/sshd-banner
          owner: root
          group: root
          mode: '0644'

    # Update sshd configuration
      - name: Add Banner configuration to sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^Banner'
          insertafter: '# no default banner path'
          line: 'Banner /etc/ssh/sshd-banner'

    # Reload sshd service
      - name: Reload sshd.service
        service:
          state: reloaded
          name: sshd.service