---
- name: Run Diagnoses on remote hosts for cve-2021-4034
  hosts: all
  become: true
  tasks:

      - name: Copy the script to {{ inventory_hostname }}
        copy:
          src: ../scripts/cve-2021-4034--2022-01-25-0936.sh
          dest: /tmp/cve-2021-4034--2022-01-25-0936.sh
          owner: root
          group: root
          mode: '0750'

      - name: Run Diagnose on {{ inventory_hostname }}
        command: /bin/bash -c "/tmp/cve-2021-4034--2022-01-25-0936.sh"
        ignore_errors: true
        register: script_results

      - name: Try to run pkexec on {{ inventory_hostname }}
        comamnd: /bin/bash -c "pkexec"
        ignore_errors: true
        register: pkexec_results

      - name: Check for stap_pkexec_block in Kernel
        comamnd: /bin/bash -c "lsmod | grep stap_pkexec_block"
        register: lsmod_results
        failed_when: "script_results.rc != 0 and not pkexec_results.stdout is search('Killed') and not lsmod_results.stdout is search('stap_pkexec_block')"
