---
- hosts: all
  become: true
  remote_user: root
  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present

        - name: Deploy SSH Key
          ansible.posix.authorized_key:
                  user: ansible
                  state: present
                  key: "{{ lookup ('file','/home/root/.ssh/id_rsa.pub')}}"

        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'
