---
- hosts: all
  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present


        - name: Copy public key to rmeote server
          copy:
              src: /root/.ssh/id_rsa.pub
              dest: /root
              mode: "0644"
              remote_src: True


        - name: if this file does not exist, FAIL (this is the default)
          debug: msg="{{ query('file', '/tmp/id_rsa.pub', errors='warn') }}"

        - stat:
            path: "{{ '/root/.ssh/id_rsa.pub' }}"
          register: has_key
          delegate_to: 127.0.0.1


        - name: Copy public key to ansible
          authorized_key:
             user: ansible
             state: present
             key: "{{ lookup('file', '/.ssh/'+'id_rsa.pub') }}"
          when: (has_key.stat.exists == True)
        

        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'
