---
- hosts: all
  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present


        - name: Copy public key to rmeote server
          copy:
              src: /root/.ssh/id_rsa.pub
              dest: /root
              mode: "0644"
              remote_src: True


        - name: if this file does not exist, FAIL (this is the default)
          debug: msg="{{ query('file', '/root/.ssh/id_rsa.pub', errors='strict') }}"


        - name: Copy public key to ansible
          authorized_key:
             user: ansible
             state: present
             key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        

        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'
