---
- hosts: all
  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present

        - name: Copy public key to rmeote server
          copy: 
             src: /root/.ssh/id_rsa.pub
             dest: /root

        - name: Copy private key to ansible
          authorized_key:
             user: ansible
             state: present
             manage_dir: yes
             key: "{{ lookup('file', '/root/id_rsa.pub' }}"
        

        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'
