---
- hosts: all
  become: yes
  vars:
      pubkey: "{{ lookup('file', '~/id_rsa.pub') }}"

  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present


        - name: Set authorized key for user ansible copying it from current user
          authorized_key:
             user: ansible
             state: present
             key: "{{ pubkey }}"

        #- name: Copy public key to rmeote server
         # copy:
          #    src: "~/id_rsa.pub"
           #   dest: /root
            #  mode: "0644"


        #- name: Create .ssh folder
        #  command: mkdir /home/ansible/.ssh; cat /root/id_rsa.pub >> /home/ansible/.ssh/authorized_keys; chmod 700 /home/ansible/.ssh; chmod 600 /home/ansible/.ssh/authorized_keys
        

        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'
