---
- hosts: all
  become: true
  gather_facts: no
  vars:
      admin_ssh_public_key: "{{ ssh_public_key | d(admin_public_sshkey) }}"
      pubkey: "{{ lookup('file', admin_ssh_public_key) }}"

  tasks:

        - name: Create a new user - 'ansible'
          user: 
             name: ansible
             password: $6$testing$Dsf3AUPPMRquaHjogzFHUx5jzqP2o8oEB1Yju5hTHFN74Clztb8ZEEpjlsyDdKpiGuSbcqmgNSMcRiyeyINcE.
             state: present


        - name: Set authorized key for user ansible copying it from current user
          authorized_key:
             user: ansible
             state: present
             key: "{{ pubkey }}"


        - name: Add the LinuxAdmins AD Group to sudoers
          lineinfile:
            dest: /etc/sudoers
            line: 'ansible       ALL=(ALL)       NOPASSWD: ALL'
            insertafter: '^%wheel'

        - name: Change user password for admin user
          user:
            name: '{{ lookup("env","SAT_USERNAME") }}'
            update_password: always
            password: '{{ lookup("env","SAT_PASSWORD") }}'
