---
- hosts: satellite
  become: true
  remote_user: ansible

  tasks: 

      - name: Clone/Update repository to destination
        git:
            repo: 'https://github.com/mordan34/weizmann.git'
            dest: /opt/weizmann
            clone: yes
            update: yes
            force: yes

      - name: Add new host record in Infoblox for {{ hostname }}
        command: "/usr/bin/ansible-playbook /root/weizmann/playbooks/addnewrecord.yml -e hostname={{ hostname }}"
        delegate_to: iblanstwtstv01t.weizmann.ac.il
        connection: local
      
      - name: Execute Hammer script to create server {{ hostname }}
        command: /bin/bash -c "/opt/weizmann/scripts/createhost.sh {{ hostname }} "
