---
- hosts: satellite
  become: true
  remote_user: ansible
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault
  vars:
    username: '{{ lookup("env","SAT_USERNAME") }}'
    password: '{{ lookup("env","SAT_PASSWORD") }}'

  tasks: 

      - name: Clone/Update repository to destination
        git:
            repo: 'https://github.com/mordan34/weizmann.git'
            dest: /opt/weizmann
            clone: yes
            update: yes
            force: yes
      
      - name: Execute Hammer script to create server {{ hostname }}
        command: /bin/bash -c "/opt/weizmann/scripts/createhost.sh {{ hostname }} "

      - name: Print username from Ansible Tower
        debug:
          msg: "{{ username }} : {{ password }}"

      - name: Initiate Cyberm8 Task for {{ hostname }}
        command: /usr/bin/python /opt/weizmann/scripts/openrules.py "{{ hostname }}"
