---
- hosts: all
  become: true

  tasks: 

      - name: Clone/Update repository to destination
        git:
            repo: 'https://github.com/mordan34/weizmann.git'
            dest: /opt
            clone: yes
            update: yes


      - name: Execute Hammer script to create a new server
        command: /bin/bash -c "/opt/weizmann/scripts/createhost.sh {{ hostname }} "
        delegate_to: iblstlv01.weizmann.ac.il
