---
- hosts: all
  become: true

  tasks: 

      - name: Execute Hammer script to create a new serve
        command: /bin/bash -c "/root/weizmann/scripts/createhost.sh {{ hostname }} "
        delegate_to: iblstlv01.weizmann.ac.il
