---
- name: Import all networks from ipam and creates on Satellite server
  hosts: all
  become: true
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault

  tasks:
    - name: Get all ipam networks
      uri:
        follow_redirects: none
        validate_certs: false
        timeout: 20
        method: GET
        url: "https://{{ nios_hostname }}/wapi/v2.9/network?_max_results=10000"
        url_username: "{{ nios_user }}"
        url_password: "{{ nios_password }}"
      register: networks | from_json
      failed_when: false


    - name: Prints all networks
      debug:
        msg: "{{ item }}"
      loop: "{{ networks }}"
