---
- hosts: all
  become: true
  become_user: root

  tasks: 

      - name: Copy Banner to ssh daemon folder
        copy: 
          src: ../templates/sshd-banner
          dest: /etc/ssh/sshd-banner
          owner: root
          group: root
          mode: '0644'

      - name: Add Banner configuration to sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^Banner'
          insertafter: '# no default banner path'
          line: 'Banner /etc/ssh/sshd-banner'

      - name: Register sshd process ID
        command: "cat /var/run/sshd.pid"
        register: sshd_pid

      - name: Reload sshd.service
        service:
          state: reloaded
          name: sshd.service