---
- name: Add existing hosts to Satellite server
  hosts: all
  become: true

  tasks: 
     
     - include_tasks: ../tasks/updatessl.yml
       ignore_errors: true

     - include_tasks: ../tasks/register.yml
       when:  ansible_facts["os_family"] == "RedHat"
       ignore_errors: true