---
- name: Add existing hosts to Satellite server
  hosts: all
  become: true

  tasks: 
     
     - include_tasks: ../tasks/register.yml
       name: Register Red Hat hosts to Satellite
       when:  ansible_facts["os_family"] == "RedHat"