---
- name: Add existing hosts to Satellite server
  hosts: all
  become: true
  gather_facts: no

  tasks: 
     
     - name: Initiate Cyberm8 Task for {{ inventory_hostname }}
       environment:
          username: '{{ lookup("env","SAT_USERNAME") }}'
          password: '{{ lookup("env","SAT_PASSWORD") }}'
       command: /usr/bin/python /opt/weizmann/scripts/openrules.py "{{ inventory_hostname }}"
       delegate_to: 127.0.0.1


     - name: Copy registration script to remote host
       copy:
          src: ../scripts/registerrh.sh
          dest: /tmp/registerrh.sh
          owner: ansible
          group: ansible
          mode: 0770

     - name: Register host with Satellite
       command: /tmp/registerrh.sh
     
