- name: Remove all networks from ipam and creates on Satellite server
  hosts: satellite
  become: true
  vars_files:
    - ../group_vars/nios.yml
    - ../group_vars/vault

  tasks:
    - name: Get all ipam networks
      uri:
        follow_redirects: none
        validate_certs: true
        timeout: 20
        method: GET
        url: "https://{{ nios_hostname }}/wapi/v{{ nios_provider.wapi_version }}/network?_max_results=10000"
        url_username: "{{ nios_user }}"
        url_password: "{{ nios_password }}"
      register: networks_json
      failed_when: false

    - set_fact: 
        networks: "{{ networks_json.json | list }}"

    - name: Removes all subnets under Satellite
      redhat.satellite.subnet:
        name: "Range-Subnet {{ item.network }}"
        description: "{{ item | selectattr('comment', 'defined')}}"
        network: "{{ item.network | ipaddr('network') }}"
        mask: "{{ item.network | ipaddr('netmask') }}"
        dhcp_proxy: "{{ inventory_hostname }}"
        tftp_proxy: "{{ inventory_hostname }}"
        dns_proxy: "{{ inventory_hostname }}"
        server_url: "https://{{ inventory_hostname }}"
        username: 
        password: 
        state: absent
      loop: "{{ networks }}"
      when: networks | length > 0
