---
- name: Upgrade PHP version
  hosts: all
  become: true
  remote_user: root

  tasks:
      - name: Update package ca-certificates
        yum:
          name: ca-certificates
          state: latest

      - name: Remove PHP packages
        yum:
          name: php*
          state: absent