- name: Remove all networks from ipam and creates on Satellite server
  hosts: satellite
  become: true
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault

  tasks:
    - name: Get all ipam networks
      uri:
        follow_redirects: none
        validate_certs: true
        timeout: 20
        method: GET
        url: "https://{{ nios_hostname }}/wapi/v{{ nios_provider.wapi_version }}/network?_max_results=1000"
        url_username: "{{ nios_user }}"
        url_password: "{{ nios_password }}"
      register: networks_json
      failed_when: false


    - set_fact: 
        networks: "{{ networks_json | list }}"


    - name: Creates all subnets under Satellite
      redhat.satellite.subnet:
        name: "Subnet {{ item.network }}"
        description: "{{ item | selectattr('comment', 'defined')}}"
        network: "{{ item.network | ipaddr('network') }}"
        mask: "{{ item.network | ipaddr('netmask') }}"
        domains:
          - "weizmann.ac.il"
        organizations:
          - "Weizmann Institute of Science"
        locations:
          - "Weizmann Lan"
        server_url: "https://{{ inventory_hostname }}"
        username: 'admin'
        password: 'ya4HeEhkAjhsdbzs'
        state: absent
      loop: "{{ networks }}"