---
- hosts: localhost
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault

  connection: local
  tasks:
   
    - name: Fetch host {{ hostname }}
      set_fact:
              host: "{{ lookup('nios', 'record:host', filter={'name~':hostname}, provider=nios_provider) }}"

    - name: Check the {{ hostname }} return variable
      debug:
        msg: "{{ host }}"

    - name: Show {{ hostname }} IPV4 address
      debug:
        msg: "{{ host.ipv4addrs[0].ipv4addr }}"
