---
- hosts: localhost
  vars_files:
    - inventory/group_vars/nios.yml
    - inventory/group_vars/vault

  connection: local
  tasks:
    - name: Assign Variable with Single quotes
      set_fact:
        hostname_str:  "'{{ hostname }}'"

    - name: Check the hostname_str Value
      debug:
        msg: "{{ hostname_str }}"
   
    - name: Fetch host {{ hostname_str }}
      set_fact:
        host: "{{ lookup('nios', 'record:a', filter={'name~':'iblvctest0'}, provider=nios_provider) }}"

    - name: Check the {{ hostname }} return variable
      debug:
        msg: "{{ host }}"

    - name: Show {{ hostname }} IPV4 address
      debug:
        msg: "{{ host.ipv4addr }}"
