---
- name: Upgrade PHP version
  hosts: all
  become: true
  vars:
    php_version: "{{ version }}"
    php_versions_install_recommends: true
  remote_user: root

  tasks:
      - name: Update package ca-certificates
        yum:
          name: ca-certificates
          state: latest

      - name: Remove PHP packages
        yum:
          name: php*
          state: absent
          
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php
