---
- name: Upgrade PHP version
  hosts: php
  become: true
  vars:
    currentphp: "{{ lookup('vars', php_ver) }}"
    php_version: "{{ version }}"
    php_versions_install_recommends: true
    php_packages_extra:
       - php-mysqlnd
       - php-bcmath
       - php-soap
       - php-pecl-json-post
       - php-pecl-mcrypt
       - php-pecl-zip
       - php-oci8

  pre_tasks:
    
    - include: ../tasks/updatecacer.yml
    - include: ../tasks/removephp.yml

    - name: Backup important files
      command: /bin/sh -c "mkdir /opt/phpbackup/; 
                               cp /etc/php.ini /opt/phpbackup/php.ini; 
                               php -m 2>&1 >> /opt/phpbackup/php_m.log; 
                               rpm -qa | grep php 2>&1 >> /opt/phpbackup/php_rpm.log"
          
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php

  post_tasks:
    - name: Copy all modules from remi's install location to module dir target
      copy:
        src: "{{ currentphp.remi_modulepath }}/*.so"
        dest: "{{ currentphp.modulepath }}"
        remote_src: yes
      ignore_errors: true

    - include: ../tasks/installoci8.yml

    - include: ../tasks/imagemagick.yml
      notify: Restart apache


  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
      
    
