---
- name: Upgrade PHP version
  hosts: all
  become: true
  vars:
    php_version: "{{ version }}"
    php_versions_install_recommends: true
  remote_user: root
          
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php
