---
- name: Upgrade PHP version
  hosts: php
  vars:
    php_version: '8.0'
    php_versions_install_recommends: true
  remote_user: root
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php
