---
- name: Upgrade PHP version
  hosts: all
  become: true
  vars_files:
    - ./inventory/group_vars/php.yml
  vars:
    currentphp: "{{ lookup('vars', php_ver) }}"
    php_version: "{{ version }}"
    php_versions_install_recommends: true
    php_packages_extra:
       - php-mysqlnd
       - php-bcmath
       - php-soap
       - php-pecl-json-post
       - php-pecl-mcrypt
       - php-pecl-zip
       - php-oci8
       - php-intl

  pre_tasks:
    - name: Backup important files
      command: /bin/sh -c "mkdir /opt/phpbackup/; 
                               cp /etc/php.ini /opt/phpbackup/php.ini; 
                               php -m 2>&1 >> /opt/phpbackup/php_m.log; 
                               rpm -qa | grep php 2>&1 >> /opt/phpbackup/php_rpm.log"

    - include_tasks: ../tasks/updatessl.yml
    - include_tasks: ../tasks/removephp.yml
          
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - role: geerlingguy.php


  post_tasks:
    - name: Copy all modules from remi's install location to module dir target
      copy:
        src: "{{ currentphp.remi_modulepath }}/*.so"
        dest: "{{ currentphp.modulepath }}"
        remote_src: yes
      ignore_errors: true

    - include_tasks: ../tasks/installoci8.yml

    - include_tasks: ../tasks/imagemagick.yml
      notify: Restart webserver


  handlers:
    - name: Restart webserver
      ansible.builtin.service:
        name:  "{{ php_webserver_daemon }}"
        state: restarted
      
    
